# Generated by Django 5.2.1 on 2025-06-15 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigAutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_column='nombre', unique=True)),
                ('puede_emitir', models.BooleanField(db_column='puede_emitir', default=False)),
                ('puede_recibir', models.BooleanField(db_column='puede_recibir', default=False)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.BigAutoField(db_column='id_persona', primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_column='nombre')),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('direccion', models.TextField(blank=True, db_column='direccion', null=True)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=15, null=True)),
                ('password', models.TextField(db_column='password')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='fecha_modificacion')),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas_creadas', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='persona_set', to='auth.group', verbose_name='groups')),
                ('modificado_por', models.ForeignKey(blank=True, db_column='modificado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas_modificadas', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='persona_permissions_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='AsignacionRol',
            fields=[
                ('id_asignacion', models.BigAutoField(db_column='id_asignacion', primary_key=True, serialize=False)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to=settings.AUTH_USER_MODEL)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
            ],
            options={
                'db_table': 'asignacionrol',
                'unique_together': {('id_persona', 'id_rol')},
            },
        ),
    ]
