# Generated by Django 5.2.1 on 2025-06-16 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_persona_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='user_permissions',
        ),
    ]
