# Generated by Django 5.2.1 on 2025-06-23 20:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0002_configuracioncorreo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('error', 'Error')], max_length=10)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(default=datetime.datetime.now)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio_correo', to='facturas.factura')),
            ],
        ),
    ]
