# Generated by Django 5.2.1 on 2025-06-16 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_remove_persona_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', max_length=20)),
                ('archivo_pdf', models.FileField(upload_to='facturas/')),
                ('periodo', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('intereses_por_mora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_emitidas', to='usuarios.asignacionrol')),
                ('id_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_recibidas', to='usuarios.asignacionrol')),
            ],
        ),
        migrations.CreateModel(
            name='EnvioFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(default='email', max_length=50)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_enviadas', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.factura')),
            ],
        ),
    ]
