# Generated by Django 5.2.1 on 2025-06-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_personalizado', models.TextField(default='Reciba un cordial saludo de parte de SEMDO S.A. E.S.P.\n\nLe informamos que su factura correspondiente al servicio de acueducto se encuentra disponible. A continuación, encontrará un resumen de los datos principales:\n\nAgradecemos su confianza.\n\nAtentamente,\nSEMDO S.A. E.S.P.\nServicio de Acueducto y Alcantarillado', help_text='Texto adicional del mensaje (sin incluir nombre, monto ni periodo, que se insertan automáticamente).')),
            ],
        ),
    ]
